name: 'Cache Nix store'
description: 'Cache Nix store using GitHub Actions cache to speed up workflows.'
author: 'GitHub'
inputs:
  key:
    description: 'An explicit key for restoring and saving the cache.'
    required: true
  restore-keys:
    description: 'An ordered list of keys to use for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns `false` in this case. Use `restore-key-hit` to change this behavior.'
  extra-restore-keys:
    description: 'A newline-separated list of key prefixes used for restoring multiple caches.'
    default: ''
  restore-key-hit:
    description: "When true, if a cache key matching `restore-keys` exists, it counts as a cache hit. Thus, a job won't save a new cache."
    default: 'false'

  upload-chunk-size:
    description: 'The chunk size used to split up large files during upload, in bytes.'
  fail-on-cache-miss:
    description: 'Fail the workflow if a cache entry is found neither via `key` nor via `restore-keys`.'
    default: 'false'

  gc-macos:
    description: 'When `true`, enables on `macOS` runners Nix store garbage collection before saving a cache.'
    default: 'false'
  gc-max-store-size-macos:
    description: 'Maximum Nix store size in bytes on `macOS` runners. Requires `gc-macos: true`.'
  gc-linux:
    description: 'When `true`, enables on `Linux` runners Nix store garbage collection before saving a cache.'
    default: 'false'
  gc-max-store-size-linux:
    description: 'Maximum Nix store size in bytes on `Linux` runners. Requires `gc-linux: true`.'
  
  purge:
    description: 'When `true`, purge old caches before saving a new cache with a `key`.'
    default: 'false'
  purge-keys:
    description: 'A newline-separated list of cache key prefixes used to purge caches. An empty string is equivalent to the `key` input.'
    default: ''
  purge-accessed:
    description: 'When `true`, purge caches by `last accessed` time. Requires `purge: true`.'
    default: 'false'
  purge-accessed-max-age:
    description: 'Purge caches accessed more than this number of seconds ago. Requires `purge-accessed: true`.'
    default: '604800'
  purge-created:
    description: 'When `true`, purge caches by `created` time. Requires `purge: true`.'
    default: 'true'
  purge-created-max-age:
    description: 'Purge caches created more than this number of seconds ago. Requires `purge-created: true`.'
    default: '604800'
  
  token:
    description: 'Used to communicate with GitHub API.'
    default: ${{ github.token }}
    required: true
outputs:
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key.'
  cache-primary-key:
    description: 'A resolved cache key for which cache match was attempted'
  cache-matched-key:
    description: 'Key of the cache that was restored, it could either be the primary key on cache-hit or a partial/complete match of one of the restore keys'
runs:
  using: 'node16'
  main: 'dist/restore/index.js'
  post: 'dist/save/index.js'
  post-if: success()
branding:
  icon: 'archive'
  color: 'gray-dark'
