name: 'Save a cache'
description: 'Save Cache artifacts like dependencies and build outputs to improve workflow execution time'
author: 'GitHub'
inputs:
  path:
    description: 'A list of files, directories, and wildcard patterns to cache'
    required: true
  key:
    description: 'An explicit key for saving the cache'
    required: true
  upload-chunk-size:
    description: 'The chunk size used to split up large files during upload, in bytes'
    required: false
  enableCrossOsArchive:
    description: 'An optional boolean when enabled, allows windows runners to save caches that can be restored on other platforms'
    default: 'false'
    required: false
  
  gc-macos:
    description: 'When `true`, enables on `macOS` runners Nix store garbage collection before saving a cache.'
    default: 'false'
  gc-max-store-size-macos:
    description: 'Maximum Nix store size in bytes on `macOS` runners. Requires `gc-macos: true`.'
  gc-linux:
    description: 'When `true`, enables on `Linux` runners Nix store garbage collection before saving a cache.'
    default: 'false'
  gc-max-store-size-linux:
    description: 'Maximum Nix store size in bytes on `Linux` runners. Requires `gc-linux: true`.'
  
  purge:
    description: 'When `true`, purge old caches before saving a new cache with a `key`.'
    default: 'false'
  purge-keys:
    description: 'A newline-separated list of cache key prefixes used to purge caches. An empty list is equivalent to the `key` input.'
    required: false
  purge-accessed:
    description: 'When `true`, purge caches by `last accessed` time. Requires `purge: true`.'
    default: 'false'
  purge-accessed-max-age:
    description: 'Purge caches accessed more than this number of seconds ago. Requires `purge-accessed: true`.'
    default: '604800'
  purge-created:
    description: 'When `true`, purge caches by `created` time. Requires `purge: true`.'
    default: 'true'
  purge-created-max-age:
    description: 'Purge caches created more than this number of seconds ago. Requires `purge-created: true`.'
    default: '604800'
  
  token:
    description: 'Used to communicate with GitHub API.'
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: '../dist/save-only/index.js'
branding:
  icon: 'archive'
  color: 'gray-dark'
